version: '3.8'

services:
  api:
    image: chabu/docker-serverless:slim
    volumes:
      - .:/home/node/workspace
    ports:
      - 4000:3000
    tty: true
    stdin_open: true
    command: npm run start
