service: api-posts

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev
  versionFunctions: false
  deploymentBucket: zadif-sls-deployments

plugins:
  - serverless-webpack
  # - serverless-offline

# package:
#   individually: true

custom:
  webpack:
    includeModules: true

functions:
  graphql:
    handler: lambda.graphql
    events:
      - http:
          path: /
          method: post
          cors:
            origins:
              - https://api.zadif.com
      - http:
          path: /
          method: get
          cors:
            origins:
              - https://api.zadif.com
