FROM node:14-slim
# RUN npm i -g typescript@3.9.2
RUN yarn global add serverless@1.71.1
RUN npm i -g serverless@1.71.1
# RUN npm config set prefix /usr/local
# RUN export PATH="$PATH:$(yarn global bin)"
