name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/steve
      - uses: actions/checkout@v2

      - name: TSC -v
        run: tsc -v

      - name: SLS -v
        run: serverless -v
      # - name: Install Dependencies
      #   run: yarn install
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
