name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ./.github/actions/steve
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        run: sls -v
      # - name: Install Dependencies
      #   run: yarn install
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
