name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # - name: Install Dependencies
      #   run: yarn install

      # # need to make serverless and typescript run in parallel
      # - name: Install TypeScript
      #   run: yarn global add typescript@3.9.2

      # need to make serverless and typescript run in parallel
      - name: Install Serverless
        run: yarn global add serverless@1.71.1

      - name: Log dir
        run: yarn global dir

      - name: Log bin
        run: yarn global bin

      # # need to make serverless and typescript run in parallel
      # - name: Compile TypeScript
      #   run: tsc

      - name: Deploy
        run: yarn global list
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
