name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn

      # need to make serverless and typescript run in parallel
      - name: Compile TypeScript
        run: yarn global add typescript@3.9.2

      # need to make serverless and typescript run in parallel
      - name: Install Serverless
        run: yarn global add serverless@1.71.1

      # need to make serverless and typescript run in parallel
      - uses: actions/checkout@v2
      - name: Deploy
        run: tsc && serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
