name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    container: aatlabs/serverless
    steps:
      - uses: actions/checkout@v2

      # - name: Setup Node

      # uses: ./.github/actions/steve
      - name: Install Dependencies
        run: yarn

      # - name: TSC -v ??? IT STILL WORKS WITHOUT INSTALLING IT???m CACHED?
      #   run: tsc -v

      - name: SLS -v
        run: sls -v
