name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn --production=true

      - name: Install TypeScript
        run: sudo yarn global add typescript@3.9.2 &

      - name: Install Serverless
        run: sudo yarn global add serverless@1.71.1

      - name: Compile & Deploy
        run: sudo tsc && serverless deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
